export const PRODUCTS_LOAD = 'PRODUCTS_LOAD';
export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';
export const PRODUCT_CHANGED = 'PRODUCT_CHANGED';
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';
export const PRODUCT_CREATE = 'PRODUCT_CREATE';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const PRODUCTS_RESET = 'PRODUCTS_RESET';
export const PRODUCT_CREATE_DISABLE = 'PRODUCT_CREATE_DISABLE';